import { ArrowLeft, ArrowRight, BookOpen, CheckCircle, Send } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import Button from "../components/ui/Button";
import Card from "../components/ui/Card";
import Input from "../components/ui/Input";
import { captureLeadAndOpenContent, getContentShareLink, submitSharedContentAttempt, type SharedAccess, type SharedLinkMetadata } from "../firebase/contentShareLinks";
import { parseOnlineExamination } from "../utils/onlineExaminationParser";

type PublicQuestion={id:string;number?:number;order?:number;questionText?:string;prompt?:string;options:Array<{label:string;text:string}>;marks?:number;section?:string};

export default function PublicSharedContentPage(){
  const {code=""}=useParams();const [meta,setMeta]=useState<SharedLinkMetadata|null>(null);const [access,setAccess]=useState<SharedAccess|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [answers,setAnswers]=useState<Record<string,string>>({});const [index,setIndex]=useState(0);const [result,setResult]=useState<{score:number|null;totalMarks:number|null;percentage:number|null}|null>(null);
  const [form,setForm]=useState({fullName:"",phone:"",email:"",institutionName:"",marketingConsent:false});
  useEffect(()=>{getContentShareLink(code).then(setMeta).catch(e=>setError(e instanceof Error?e.message:"This link is unavailable.")).finally(()=>setLoading(false))},[code]);
  async function open(event:React.FormEvent){event.preventDefault();try{setBusy(true);setError("");setAccess(await captureLeadAndOpenContent({code,...form}))}catch(e){setError(e instanceof Error?e.message:"Could not open this content.")}finally{setBusy(false)}}
  const questions=useMemo<PublicQuestion[]>(()=>{if(!access)return[];if(access.contentType==="examination")return parseOnlineExamination(String(access.content.uploadedExamExtractedText||"")).map(q=>({id:String(q.number),number:q.number,prompt:q.prompt,options:q.options,section:q.section}));return Array.isArray(access.content.questions)?access.content.questions as PublicQuestion[]:[]},[access]);
  async function submit(){if(!access)return;try{setBusy(true);const answerText=questions.map((q,i)=>`${q.number??q.order??i+1}. ${answers[q.id]||"No response"}`).join("\n\n");setResult(await submitSharedContentAttempt({code,contactId:access.contactId,accessToken:access.accessToken,answers,answerText}))}catch(e){setError(e instanceof Error?e.message:"Submission failed.")}finally{setBusy(false)}}
  if(loading)return <Shell><Card>Loading shared content...</Card></Shell>;if(error&&!meta)return <Shell><Card className="border-red-200 bg-red-50 text-red-800">{error}</Card></Shell>;
  if(!access)return <Shell><Card><div className="text-center"><BookOpen className="mx-auto text-blue-700" size={48}/><p className="mt-3 text-sm font-black uppercase tracking-wide text-blue-700">{meta?.nicheName}</p><h1 className="mt-2 text-3xl font-black">{meta?.resourceTitle}</h1><p className="mt-2 text-slate-600">Shared by {meta?.tutorName}. Complete the form once to open this {meta?.contentType}.</p></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}<form onSubmit={open} className="mx-auto mt-7 max-w-xl space-y-4"><Field label="Full name" value={form.fullName} onChange={value=>setForm({...form,fullName:value})}/><Field label="Phone number" type="tel" value={form.phone} onChange={value=>setForm({...form,phone:value})}/><Field label="Email address" type="email" value={form.email} onChange={value=>setForm({...form,email:value})}/><Field label="Institution / organization" value={form.institutionName} onChange={value=>setForm({...form,institutionName:value})}/><label className="flex items-start gap-3 rounded-xl bg-slate-50 p-4 text-sm"><input className="mt-1" type="checkbox" checked={form.marketingConsent} onChange={e=>setForm({...form,marketingConsent:e.target.checked})}/><span>I agree that this tutor may contact me about relevant learning opportunities and promotions. I can withdraw this permission later.</span></label><p className="text-xs leading-5 text-slate-500">Your details are recorded for access, cohort reporting and follow-up by the tutor. Existing contacts are updated instead of duplicated.</p><Button className="w-full" disabled={busy}>{busy?"Opening...":"Continue to Content"}</Button></form></Card></Shell>;
  if(access.contentType==="lesson")return <Shell><header className="rounded-3xl bg-blue-900 p-7 text-white"><p className="text-sm font-bold text-blue-200">{access.nicheName}</p><h1 className="mt-2 text-3xl font-black">{String(access.content.title||"")}</h1><p className="mt-3 text-blue-100">{String(access.content.description||"")}</p></header><LessonContent content={access.content}/></Shell>;
  if(result)return <Shell><Card className="text-center"><CheckCircle className="mx-auto text-emerald-600" size={54}/><h1 className="mt-4 text-2xl font-black">Submission received</h1>{result.score!=null?<p className="mt-4 text-xl font-bold text-blue-900">Score: {result.score}/{result.totalMarks} ({result.percentage}%)</p>:<p className="mt-3 text-slate-600">Your tutor can now review and analyse this submission with the rest of the {access.nicheName} cohort.</p>}</Card></Shell>;
  const question=questions[index];if(!question)return <Shell><Card>No readable questions were found in this content. Please contact the tutor.</Card></Shell>;
  return <Shell><header className="mb-5 rounded-2xl bg-slate-950 p-5 text-white"><p className="text-sm text-slate-300">{access.nicheName}</p><h1 className="text-xl font-black">{String(access.content.title||"")}</h1><p className="mt-2 text-sm">Question {index+1} of {questions.length}</p></header><Card><p className="text-sm font-black uppercase text-blue-700">{question.section||`Question ${question.order??index+1}`}</p><h2 className="mt-3 text-lg font-bold leading-8">{question.prompt||question.questionText}</h2>{question.options?.length?<div className="mt-5 space-y-3">{question.options.map(option=><label key={option.label} className={`flex cursor-pointer gap-3 rounded-xl border p-4 ${answers[question.id]===option.label?"border-blue-600 bg-blue-50":""}`}><input type="radio" checked={answers[question.id]===option.label} onChange={()=>setAnswers({...answers,[question.id]:option.label})}/><span><strong>{option.label}.</strong> {option.text}</span></label>)}</div>:<textarea className="mt-5 min-h-60 w-full rounded-xl border p-4" value={answers[question.id]||""} onChange={e=>setAnswers({...answers,[question.id]:e.target.value})} placeholder="Enter your answer..."/>}<div className="mt-6 flex justify-between gap-3"><Button variant="outline" disabled={index===0} onClick={()=>setIndex(index-1)}><ArrowLeft size={17}/>Back</Button>{index<questions.length-1?<Button onClick={()=>setIndex(index+1)}>Next<ArrowRight size={17}/></Button>:<Button disabled={busy} onClick={()=>void submit()}><Send size={17}/>{busy?"Submitting...":"Submit"}</Button>}</div></Card></Shell>
}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-slate-100 px-4 py-8"><div className="mx-auto max-w-4xl">{children}</div></main>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="block"><span className="mb-1 block text-sm font-bold">{label}</span><Input required type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function LessonContent({content}:{content:Record<string,unknown>}){const objectives=Array.isArray(content.learningObjectives)?content.learningObjectives as Array<Record<string,unknown>>:[];const sections=Array.isArray(content.sections)?content.sections as Array<Record<string,unknown>>:[];const blocks=Array.isArray(content.blocks)?content.blocks as Array<Record<string,unknown>>:[];return <div className="mt-5 space-y-5">{objectives.length>0&&<Card><h2 className="text-xl font-black">Learning objectives</h2><ul className="mt-3 list-disc space-y-2 pl-6">{objectives.map((o,i)=><li key={i}>{String(o.objective||o.title||"")}</li>)}</ul></Card>}{sections.map((section,i)=><Card key={String(section.id||i)}><h2 className="text-xl font-black">{String(section.title||`Section ${i+1}`)}</h2><p className="mt-3 whitespace-pre-wrap leading-8">{String(section.content||"")}</p></Card>)}{blocks.map((block,i)=><Card key={String(block.id||i)}><h2 className="font-black">{String(block.title||block.type||`Learning item ${i+1}`)}</h2><p className="mt-3 whitespace-pre-wrap leading-8">{String(block.content||block.text||block.description||"")}</p></Card>)}</div>}

