import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import TutorLayout from "../components/layout/TutorLayout";
import Button from "../components/ui/Button";
import Card from "../components/ui/Card";
import { deleteQuestion, getQuestionById, updateQuestion } from "../firebase/questions";
import type { BloomLevel, Question, QuestionDifficulty, QuestionType } from "../models/Question";

export default function QuestionDetailsPage({ edit = false }: { edit?: boolean }) {
  const { questionId } = useParams(); const navigate = useNavigate();
  const [question, setQuestion] = useState<Question | null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  useEffect(()=>{ if(!questionId)return; void getQuestionById(questionId).then(setQuestion).finally(()=>setLoading(false)); },[questionId]);
  async function save(e:React.FormEvent){e.preventDefault(); if(!questionId||!question)return; setSaving(true); try{await updateQuestion(questionId,question); navigate(`/tutor/questions/${questionId}`)}finally{setSaving(false)}}
  async function remove(){if(!questionId||!window.confirm("Delete this question permanently?"))return; await deleteQuestion(questionId); navigate("/tutor/questions")}
  if(loading)return <TutorLayout title="Question" subtitle="Loading question..."><Card>Loading...</Card></TutorLayout>;
  if(!question)return <TutorLayout title="Question Not Found" subtitle="The question may have been deleted."><Card><Button onClick={()=>navigate("/tutor/questions")}>Back to Question Bank</Button></Card></TutorLayout>;
  if(!edit)return <TutorLayout title="View Question" subtitle="Review question details and answers."><Card><div className="flex flex-wrap gap-2 text-sm"><Badge>{question.topic}</Badge><Badge>{question.type}</Badge><Badge>{question.difficulty}</Badge><Badge>{question.bloomLevel}</Badge><Badge>{question.marks} marks</Badge></div><h2 className="mt-5 text-2xl font-bold">{question.questionText}</h2>{question.options?.length>0&&<ol className="mt-5 list-[upper-alpha] space-y-2 pl-8">{question.options.map(o=><li key={o.id}>{o.text}</li>)}</ol>}<div className="mt-6 rounded-xl bg-green-50 p-4"><strong>Correct answer:</strong> {question.correctAnswer}</div><div className="mt-4 rounded-xl bg-slate-50 p-4"><strong>Explanation:</strong> {question.explanation||"No explanation provided."}</div><div className="mt-6 flex gap-3"><Button onClick={()=>navigate(`/tutor/questions/${question.id}/edit`)}>Edit</Button><Button variant="outline" onClick={()=>void remove()}>Delete</Button></div></Card></TutorLayout>;
  return <TutorLayout title="Edit Question" subtitle="Update the selected question."><Card><form onSubmit={save} className="space-y-5"><Field label="Question text"><textarea className="min-h-32 w-full rounded-xl border p-3" value={question.questionText} onChange={e=>setQuestion({...question,questionText:e.target.value})}/></Field><div className="grid gap-4 md:grid-cols-3"><Field label="Topic"><input className="w-full rounded-xl border p-3" value={question.topic} onChange={e=>setQuestion({...question,topic:e.target.value})}/></Field><Field label="Type"><select className="w-full rounded-xl border p-3" value={question.type} onChange={e=>setQuestion({...question,type:e.target.value as QuestionType})}>{["mcq","true-false","short-answer","essay","emq"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Difficulty"><select className="w-full rounded-xl border p-3" value={question.difficulty} onChange={e=>setQuestion({...question,difficulty:e.target.value as QuestionDifficulty})}>{["easy","medium","hard"].map(v=><option key={v}>{v}</option>)}</select></Field></div><Field label="Bloom level"><select className="w-full rounded-xl border p-3" value={question.bloomLevel} onChange={e=>setQuestion({...question,bloomLevel:e.target.value as BloomLevel})}>{["remember","understand","apply","analyze","evaluate","create"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Correct answer"><textarea className="min-h-20 w-full rounded-xl border p-3" value={question.correctAnswer} onChange={e=>setQuestion({...question,correctAnswer:e.target.value})}/></Field><Field label="Explanation"><textarea className="min-h-24 w-full rounded-xl border p-3" value={question.explanation} onChange={e=>setQuestion({...question,explanation:e.target.value})}/></Field><Field label="Marks"><input type="number" min="1" className="w-full rounded-xl border p-3" value={question.marks} onChange={e=>setQuestion({...question,marks:Number(e.target.value)})}/></Field><div className="flex gap-3"><Button type="submit" disabled={saving}>{saving?"Saving...":"Save Changes"}</Button><Button type="button" variant="outline" onClick={()=>navigate(`/tutor/questions/${question.id}`)}>Cancel</Button></div></form></Card></TutorLayout>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block font-semibold">{label}</span>{children}</label>}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full bg-blue-100 px-3 py-1 font-semibold text-blue-800">{children}</span>}
