import { useEffect, useMemo, useState } from "react";
import TutorLayout from "../components/layout/TutorLayout";
import Button from "../components/ui/Button";
import Card from "../components/ui/Card";
import { getContentCampaigns, markSharedContentAttempt, type ContentCampaignData } from "../firebase/contentShareLinks";

export default function TutorContentCampaignResultsPage(){
  const [data,setData]=useState<ContentCampaignData>({links:[],contacts:[],attempts:[]});const [selected,setSelected]=useState("all");const [saving,setSaving]=useState("");
  async function load(){setData(await getContentCampaigns())}
  useEffect(()=>{void load().catch(()=>undefined)},[]);
  const contacts=useMemo(()=>new Map(data.contacts.map(item=>[String(item.id),item])),[data.contacts]);
  const filtered=useMemo(()=>data.attempts.filter(item=>selected==="all"||String(item.assessmentGroupId)===selected),[data.attempts,selected]);
  const marked=filtered.filter(item=>Number.isFinite(Number(item.percentage)));const average=marked.length?Math.round(marked.reduce((sum,item)=>sum+Number(item.percentage),0)/marked.length):null;
  async function mark(attempt:Record<string,unknown>){const total=Number(prompt("Total marks:",String(attempt.totalMarks||100)));const score=Number(prompt(`Score out of ${total}:`,String(attempt.score||0)));if(!Number.isFinite(total)||!Number.isFinite(score)||total<=0||score<0||score>total)return alert("Enter a valid score.");const feedback=prompt("Tutor feedback / corrections:",String(attempt.feedback||""))||"";try{setSaving(String(attempt.id));await markSharedContentAttempt({attemptId:String(attempt.id),score,totalMarks:total,feedback});await load()}finally{setSaving("")}}
  return <TutorLayout title="Campaign Results" subtitle="Compare submissions, marks and performance by niche or content campaign."><div className="grid gap-4 sm:grid-cols-3"><Metric label="Submissions" value={filtered.length}/><Metric label="Marked" value={marked.length}/><Metric label="Average" value={average==null?"Awaiting marks":`${average}%`}/></div><Card className="mt-6"><label className="block max-w-xl"><span className="mb-1 block text-sm font-bold">Niche / campaign cohort</span><select className="w-full rounded-xl border px-3 py-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="all">All campaign cohorts</option>{data.links.map(link=><option key={String(link.id)} value={String(link.assessmentGroupId||link.code||link.id)}>{String(link.nicheName)} — {String(link.resourceTitle)}</option>)}</select></label></Card><Card className="mt-6"><h2 className="text-xl font-black">Collective grading and analysis</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Participant</th><th className="p-3">Institution</th><th className="p-3">Niche</th><th className="p-3">Content</th><th className="p-3">Score</th><th className="p-3">Action</th></tr></thead><tbody>{filtered.map(attempt=>{const contact=contacts.get(String(attempt.contactId));return <tr key={String(attempt.id)} className="border-b"><td className="p-3"><strong>{String(contact?.fullName||"Lead")}</strong><br/><span className="text-xs text-slate-500">{String(contact?.email||"")}</span></td><td className="p-3">{String(contact?.institutionName||"")}</td><td className="p-3">{String(attempt.nicheName||"")}</td><td className="p-3">{String(attempt.resourceTitle||"")}</td><td className="p-3 font-bold">{attempt.score==null?"Tutor review":`${String(attempt.score)}/${String(attempt.totalMarks)} (${String(attempt.percentage)}%)`}</td><td className="p-3"><Button variant="outline" disabled={saving===String(attempt.id)} onClick={()=>void mark(attempt)}>{attempt.status==="marked"?"Review mark":"Mark"}</Button></td></tr>})}</tbody></table>{filtered.length===0&&<p className="py-8 text-center text-slate-500">No submissions in this cohort yet.</p>}</div></Card></TutorLayout>
}
function Metric({label,value}:{label:string;value:string|number}){return <Card><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></Card>}

