import { Bot, ExternalLink, Send, X } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import useAuth from "../../../hooks/useAuth";
import { DocumentationAssistantService } from "../application/documentation-assistant-service";
import type { DocumentationAssistantResult } from "../domain/assistant-models";

export default function DocumentationAssistantPanel({ open, onClose, pathname, pageTitle }: { open: boolean; onClose: () => void; pathname: string; pageTitle: string }) {
  const { role } = useAuth(); const [prompt, setPrompt] = useState(""); const [loading, setLoading] = useState(false); const [result, setResult] = useState<DocumentationAssistantResult | null>(null);
  if (!open) return null;
  const ask = async () => { const value = prompt.trim() || "Explain this page and its main workflow."; setLoading(true); setResult(await DocumentationAssistantService.ask(value, pathname, role, pageTitle)); setLoading(false); };
  return <div className="fixed inset-0 z-[90] flex justify-end bg-slate-950/35" role="dialog" aria-modal="true" aria-label="Medi documentation assistant"><aside className="h-full w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-blue-700"><Bot/><span className="font-black">Medi Platform Assistant</span></div><p className="mt-1 text-sm text-slate-500">{pageTitle}</p></div><button type="button" onClick={onClose} className="rounded-xl border p-2"><X size={20}/></button></div><div className="mt-6 flex gap-2"><input value={prompt} onChange={(event)=>setPrompt(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter") void ask();}} placeholder="Ask how to use this page" className="min-w-0 flex-1 rounded-xl border px-4 py-3"/><button type="button" disabled={loading} onClick={()=>void ask()} className="rounded-xl bg-blue-700 px-4 text-white disabled:opacity-60"><Send size={18}/></button></div><button type="button" onClick={()=>{setPrompt("Explain this page and its main workflow."); void DocumentationAssistantService.ask("Explain this page and its main workflow.", pathname, role, pageTitle).then(setResult);}} className="mt-3 text-sm font-bold text-blue-700">Explain This Page</button>{loading && <p className="mt-6 text-sm text-slate-500">Medi is checking the Knowledge Center…</p>}{result && <div className="mt-6 space-y-5"><div className="whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-800">{result.answer}</div>{result.actions.length>0 && <div className="flex flex-wrap gap-2">{result.actions.map((action)=><Link key={action.routeKey} to={action.path} onClick={onClose} className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white">{action.label}</Link>)}</div>}{result.articles.length>0 && <div><h3 className="font-black">Related articles</h3><div className="mt-2 space-y-2">{result.articles.map((article)=><Link key={article.id} to={`/help/articles/${article.slug}`} onClick={onClose} className="flex items-center justify-between rounded-xl border p-3 text-sm font-bold hover:border-blue-300">{article.title}<ExternalLink size={15}/></Link>)}</div></div>}</div>}</aside></div>;
}
