import { Clock3, Heart, ShoppingBag, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { collection, getDocs, limit, orderBy, query, where } from "firebase/firestore";
import { db } from "../../config/firebase";
import { MarketplaceIntelligenceService, MarketplaceService, type MarketplaceProduct } from "../../domains/marketplace";
import useAuth from "../../hooks/useAuth";

export default function MarketplaceBuyerInsightsPage(){const {currentUser}=useAuth();const [recent,setRecent]=useState<MarketplaceProduct[]>([]);const [recommended,setRecommended]=useState<MarketplaceProduct[]>([]);useEffect(()=>{if(!currentUser)return;void (async()=>{const viewed=await getDocs(query(collection(db,"recentlyViewed"),where("customerUid","==",currentUser.uid),orderBy("viewedAt","desc"),limit(8)));const ids=viewed.docs.map(d=>String(d.get("productId")));const items=(await Promise.all(ids.map(id=>MarketplaceService.getProduct(id)))).filter(Boolean) as MarketplaceProduct[];setRecent(items);if(items[0])setRecommended(await MarketplaceIntelligenceService.listRecommendations(items[0],8));else setRecommended(await MarketplaceIntelligenceService.listTrending(8));})();},[currentUser]);const Section=({title,items}:{title:string;items:MarketplaceProduct[]})=><section className="mt-7 rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{items.map(item=><Link key={item.id} to={`/marketplace/products/${item.id}`} className="rounded-xl border p-4 hover:border-cyan-400"><p className="font-black">{item.title}</p><p className="mt-2 text-sm text-slate-600 line-clamp-2">{item.shortDescription}</p><p className="mt-3 text-sm font-bold text-cyan-700">{item.price.currency} {item.price.amount.toLocaleString()}</p></Link>)}</div></section>;
return <main className="min-h-screen bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase text-cyan-700">My Marketplace</p><h1 className="text-3xl font-black">Learning and purchase insights</h1><div className="mt-7 grid gap-4 sm:grid-cols-4">{[["Orders","/marketplace/orders",ShoppingBag],["Wishlist","/marketplace/wishlist",Heart],["Recently viewed","#recent",Clock3],["Recommended","#recommended",Sparkles]].map(([label,to,Icon])=><Link key={String(label)} to={String(to)} className="rounded-2xl border bg-white p-5 font-bold"><Icon className="mb-3 text-cyan-700"/>{String(label)}</Link>)}</div><div id="recent"><Section title="Recently viewed" items={recent}/></div><div id="recommended"><Section title="Recommended for you" items={recommended}/></div></div></main>}
