import { Search, Store, Star, BookOpen, Filter } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { filterMarketplaceProducts, useMarketplace } from "../../domains/marketplace";

function money(amount: number, currency: string) { return new Intl.NumberFormat("en-UG", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount); }
export default function MarketplaceHomePage() {
  const { products, categories, loading, error } = useMarketplace();
  const [term, setTerm] = useState(""); const [category, setCategory] = useState(""); const [type, setType] = useState(""); const [minimumRating,setMinimumRating]=useState(0); const [sort,setSort]=useState("newest");
  const filtered = useMemo(() => { const base=filterMarketplaceProducts(products, term, category, type).filter(item=>item.ratingAverage>=minimumRating); return [...base].sort((a,b)=>sort==="best_selling"?b.salesCount-a.salesCount:sort==="rating"?b.ratingAverage-a.ratingAverage:sort==="price_low"?a.price.amount-b.price.amount:sort==="price_high"?b.price.amount-a.price.amount:0); }, [products, term, category, type, minimumRating, sort]);
  return <div className="min-h-screen bg-slate-50">
    <header className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="flex items-center gap-3 text-cyan-300"><Store/><span className="font-bold uppercase tracking-widest">Medical Elites Marketplace</span></div><h1 className="mt-5 max-w-4xl text-4xl font-black sm:text-6xl">Health sciences learning, built by educators who understand the field.</h1><p className="mt-5 max-w-3xl text-lg text-slate-300">Discover courses, lessons, question banks, mock examinations, videos and professional study resources.</p>
    <div className="mt-8 grid gap-3 rounded-2xl bg-white/10 p-3 md:grid-cols-[1fr_180px_180px_150px_170px]"><label className="flex items-center gap-2 rounded-xl bg-white px-4 text-slate-900"><Search size={20}/><input value={term} onChange={(e)=>setTerm(e.target.value)} className="w-full bg-transparent py-3 outline-none" placeholder="Search courses, tutors or topics"/></label><select value={category} onChange={(e)=>setCategory(e.target.value)} className="rounded-xl px-4 py-3 text-slate-900"><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={type} onChange={(e)=>setType(e.target.value)} className="rounded-xl px-4 py-3 text-slate-900"><option value="">All product types</option><option value="course">Courses</option><option value="course_unit">Course units</option><option value="lesson">Lessons</option><option value="question_bank">Question banks</option><option value="mock_exam">Mock examinations</option><option value="pdf">PDF notes</option><option value="powerpoint">PowerPoints</option><option value="video">Videos</option><option value="bundle">Bundles</option></select><select value={minimumRating} onChange={(e)=>setMinimumRating(Number(e.target.value))} className="rounded-xl px-4 py-3 text-slate-900"><option value={0}>Any rating</option><option value={4}>4+ stars</option><option value={3}>3+ stars</option></select><select value={sort} onChange={(e)=>setSort(e.target.value)} className="rounded-xl px-4 py-3 text-slate-900"><option value="newest">Newest</option><option value="best_selling">Best selling</option><option value="rating">Highest rated</option><option value="price_low">Lowest price</option><option value="price_high">Highest price</option></select></div></div></header>
    <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-2xl font-black text-slate-950">Explore the catalogue</h2><p className="text-slate-600">{filtered.length} published product{filtered.length===1?"":"s"}</p></div><div className="flex flex-wrap gap-2"><Link to="/marketplace/insights" className="rounded-xl border bg-white px-4 py-3 font-bold text-cyan-800">My marketplace</Link><Link to="/marketplace/seller-analytics" className="rounded-xl border bg-white px-4 py-3 font-bold text-cyan-800">Seller analytics</Link><Link to="/marketplace/sell" className="rounded-xl bg-cyan-700 px-4 py-3 font-bold text-white hover:bg-cyan-800">Sell on Medical Elites</Link></div></div>
    {loading && <div className="rounded-2xl border bg-white p-10 text-center text-slate-600">Loading marketplace…</div>}{error && <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700">{error}</div>}{!loading && !error && filtered.length===0 && <div className="rounded-2xl border bg-white p-12 text-center"><Filter className="mx-auto text-slate-400"/><h3 className="mt-4 text-xl font-bold">No products match your filters</h3><p className="mt-2 text-slate-600">Try another category, product type or search term.</p></div>}
    <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map(p=><Link key={p.id} to={`/marketplace/products/${p.id}`} className="overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="aspect-[16/10] bg-gradient-to-br from-cyan-100 to-blue-100">{p.thumbnailUrl?<img src={p.thumbnailUrl} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center"><BookOpen size={42} className="text-cyan-700"/></div>}</div><div className="p-5"><div className="flex items-center justify-between gap-2"><span className="rounded-full bg-cyan-50 px-2.5 py-1 text-xs font-bold uppercase text-cyan-800">{p.type.replaceAll("_"," ")}</span>{p.featured&&<span className="text-xs font-bold text-amber-600">Featured</span>}</div><h3 className="mt-3 line-clamp-2 text-lg font-black text-slate-950">{p.title}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-600">{p.shortDescription}</p><p className="mt-3 text-sm font-semibold text-slate-700">{p.sellerName}</p><div className="mt-3 flex items-center justify-between"><span className="flex items-center gap-1 text-sm"><Star size={16} className="fill-amber-400 text-amber-400"/>{p.ratingAverage.toFixed(1)} <span className="text-slate-400">({p.ratingCount})</span></span><span className="font-black text-slate-950">{money(p.price.amount,p.price.currency)}</span></div></div></Link>)}</div></main>
  </div>;
}
